name: Daily Commit - 21f3000439@ds.study.iitm.ac.in

permissions:
  contents: write

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "21f3000439@ds.study.iitm.ac.in"

    - name: Make a change
      run: |
        echo "Update: $(date)" >> daily-log.txt

    - name: Commit changes
      run: |
        git add daily-log.txt
        git commit -m "Daily update: $(date)" || echo "Nothing to commit"

    - name: Push changes
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master
