name: Daily Commit Workflow

on:
  schedule:
    # Runs every day at 06:15 UTC
    - cron: "15 6 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add daily log - 21f3000439@ds.study.iitm.ac.in
        run: |
          echo "Daily timestamp: $(date -u)" >> daily.log
          git config user.name "github-actions[bot]"
          git config user.email "21f3000439@ds.study.iitm.ac.in"
          git add daily.log
          git commit -m "Daily auto-commit at $(date -u)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

